# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MyModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, demo_name=None, id=None):  # noqa: E501
        """MyModel - a model defined in OpenAPI

        :param demo_name: The demo_name of this MyModel.  # noqa: E501
        :type demo_name: str
        :param id: The id of this MyModel.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'demo_name': str,
            'id': int
        }

        self.attribute_map = {
            'demo_name': 'demoName',
            'id': 'id'
        }

        self._demo_name = demo_name
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'MyModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MyModel of this MyModel.  # noqa: E501
        :rtype: MyModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def demo_name(self):
        """Gets the demo_name of this MyModel.


        :return: The demo_name of this MyModel.
        :rtype: str
        """
        return self._demo_name

    @demo_name.setter
    def demo_name(self, demo_name):
        """Sets the demo_name of this MyModel.


        :param demo_name: The demo_name of this MyModel.
        :type demo_name: str
        """

        self._demo_name = demo_name

    @property
    def id(self):
        """Gets the id of this MyModel.


        :return: The id of this MyModel.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MyModel.


        :param id: The id of this MyModel.
        :type id: int
        """

        self._id = id
